ardi/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('terms-conditions/', TermsAndConditionsView.as_view(), name='terms_conditions'),
    path('privacy/', PrivacyView.as_view(), name='privacy'),
    path('faq/', FAQView.as_view(), name='faq'),
    path('warranty/', WarrantyView.as_view(), name='warranty'),
    path('care-maintenance/', CareAndMaintenanceView.as_view(), name='care_maintenance'),

    path('', Index.as_view(), name='index'),
    path('about/', About.as_view(), name='about'),
    path('gallery/', Galleries.as_view(), name='gallery'),
    path('products/', Products.as_view(), name='products'),
    path('products/<int:id>/', product_detail, name='product_detail'),
    path('testimonial/', Testimonials.as_view(), name='testimonials'),
    path('service/', Service.as_view(), name='service'),
    path('admin/', Dashboard.as_view(), name='dashboard'),

    path('product/', ListProduct.as_view(), name='list_product'),
    path('products/add/', AddProduct.as_view(), name='add_product'),
    path('products/edit/<int:id>/', EditProduct.as_view(), name='edit_product'),
    path('products/delete/<int:id>/', DeleteProduct.as_view(), name='delete_product'),
    path('products/image/delete/<int:id>/', DeleteProductImage.as_view(), name='delete_product_image'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('search/', ProductSearchView.as_view(), name='product_search'),


    path('galleries/', ListGallery.as_view(), name='list_gallery'),
    path('galleries/add/', AddGallery.as_view(), name='add_gallery'),
    path('galleries/edit/<int:id>/', EditGallery.as_view(), name='edit_gallery'),
    path('galleries/delete/<int:id>/', DeleteGallery.as_view(), name='delete_gallery'),
    path('galleries/image/delete/<int:id>/', DeleteImage.as_view(), name='delete_image'),

    path('testimonials/', ListTestimonial.as_view(), name='list_testimonial'),
    path('testimonials/add/', AddTestimonial.as_view(), name='add_testimonial'),
    path('testimonials/edit/<int:id>/', EditTestimonial.as_view(), name='edit_testimonial'),
    path('testimonials/delete/<int:id>/', DeleteTestimonial.as_view(), name='delete_testimonial'),

    path('contacts/', ListContact.as_view(), name='list_contact'),
    path('contacts/add/', AddContact.as_view(), name='add_contact'),
    path('contacts/delete/<int:id>/', DeleteContact.as_view(), name='delete_contact'),





    #
    #
    #
    path('homes/', ListHome.as_view(), name='list_home'),
    path('homes/add/', AddHome.as_view(), name='add_home'),
    path('homes/edit/<int:id>/', EditHome.as_view(), name='edit_home'),
    path('homes/delete/<int:id>/', DeleteHome.as_view(), name='delete_home'),
    path('homes/image/delete/<int:id>/', DeleteHomeImage.as_view(), name='delete_home_image'),
]

ardimarble/urls.py
# ardimarble/urls.py

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('ardi.urls')),
    path('useracc/', include('useracc.urls')),  # Added trailing slash
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'ardi.views.custom_404'

useracc/urls.py
from django.urls import path
from .views import *
app_name = 'useracc'

urlpatterns = [
    path('profile/<int:id>/', Profile.as_view(), name='profile'),
    path('profile/edit/', EditProfile.as_view(), name='edit_profile'),
    path('register/', Register.as_view(), name='register'),
    path('email-verify/<str:uidb64>/<str:token>/', EmailVerify.as_view(), name='email_verify'),
    path('activate/<int:user_id>/', Activate.as_view(), name='activate'),
    path('delete_user/<int:user_id>/', DeleteUser.as_view(), name='delete_user'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('staff-page/', StaffPage.as_view(), name='staff_page'),
    
]

useracc/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone

class CustomUser(AbstractUser):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('email_verified', 'Email_verified'),
        ('activated', 'Activated'),
    ]

    username = models.CharField(max_length=150, unique=True)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=13)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    is_superuser = models.BooleanField(default=False)
    profile = models.ImageField(upload_to='Profile', blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now, editable=False)

    # Override the default related_name to avoid clashes
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='customuser_set',  # Change this to avoid clashes
        blank=True
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_set',  # Change this to avoid clashes
        blank=True
    )

    def full_name(self):
        return f"{self.firstname} {self.lastname}"

    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username

useracc/forms.py
# useracc/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser

class CustomUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'firstname', 'lastname', 'gender', 'email', 'phone', 'profile']

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']
    
class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'firstname', 'lastname', 'gender', 'email', 'phone', 'profile']

useracc/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, render, redirect
from django.conf import settings
from django.utils.decorators import method_decorator
from django.utils.crypto import get_random_string
from django.views import View
from django.urls import reverse
from .forms import *
from .models import CustomUser

class Profile(LoginRequiredMixin, View):
    template_name = 'user_profile.html'

    def get(self, request, id, *args, **kwargs):
        user = get_object_or_404(CustomUser, id=id)
        return render(request, self.template_name, {'user': user})


class EditProfile(LoginRequiredMixin, View):
    template_name = 'edit_profile.html'

    def get(self, request, *args, **kwargs):
        user = request.user
        form = ProfileEditForm(instance=user)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        user = request.user
        form = ProfileEditForm(request.POST, request.FILES, instance=user)
        print("the form is correct")
        if form.is_valid():
            form.save()
            return redirect('useracc:profile', id=user.id)
        else:
            print(form.errors)  # Print form errors for debugging
        return render(request, self.template_name, {'form': form})


class Register(LoginRequiredMixin,View):
    template_name = 'register.html'

    def get(self, request, *args, **kwargs):
        form = CustomUserForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = CustomUserForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()

            # Generate email verification token
            token = default_token_generator.make_token(user)
            uidb64 = urlsafe_base64_encode(force_bytes(user.pk))

            # Build the email verification link
            current_site = get_current_site(request)
            verification_url = reverse('useracc:email_verify', kwargs={'uidb64': uidb64, 'token': token})
            verification_link = f'http://{current_site.domain}{verification_url}'

            # Send email with verification link
            subject = 'Email Verification Link'
            message = f'Click the following link to verify your email: {verification_link}'
            from_email = settings.DEFAULT_FROM_EMAIL
            to_email = [user.email]

            send_mail(subject, message, from_email, to_email, fail_silently=False)

            # Set initial status to 'pending' since email verification is pending
            user.status = 'pending'
            user.save()

            messages.success(request, 'Account created successfully. Check your email for the verification link.')
            return redirect('useracc:login')
        return render(request, self.template_name, {'form': form})
    
class EmailVerify(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = CustomUser.objects.get(pk=uid)

            if default_token_generator.check_token(user, token):
                user.status = 'email_verified'  # Updated status value
                user.save()
                messages.success(request, 'Email verification successful. Your account is now email verified.')
            else:
                messages.error(request, 'Invalid email verification token.')

        except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
            messages.error(request, 'Invalid email verification token.')

        return redirect('useracc:login')
    
class Activate(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = CustomUser.objects.get(id=user_id)
        if user.status =='email_verified':
            user.status = 'activated'
            user.save()
            messages.success(request, 'Account activation successful.')
        elif user.is_superuser==True:
            user.status='activated'
            user.save()
            messages.success(request, 'Account activation successful.')
        elif user.status=='activated':
            messages.success(request, 'the account is already activated.')

        else:
            messages.warning(request, 'User must verify their email')

        
        return redirect('useracc:staff_page')




class UserLogin(View):
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        form = CustomAuthenticationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            if user.status == 'pending' and user.is_superuser==False:
                messages.warning(request, 'Your account is pending approval. Please check your email for verification.')
                
            elif user.status == 'email_verified':
                messages.info(request, 'Your email is verified. Your account is not yet active.')
                
            elif user.status == 'activated' or user.is_superuser==True:
                login(request, user)
                messages.success(request, 'Login successful.')
                return redirect(reverse('dashboard'))
            
            
        else:
            messages.error(request, 'Invalid login credentials.')

        return render(request, self.template_name, {'form': form})
    
@method_decorator(login_required, name='dispatch')
class UserLogout(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        # request.session.set_expiry(600)
        logout(request)
        return redirect('useracc:login')

class StaffPage(LoginRequiredMixin, View):
    template_name = 'user_list.html'

    def get(self, request, *args, **kwargs):
        users = CustomUser.objects.all()
        context = {'users': users}
        return render(request, self.template_name, context)

class DeleteUser(View):
    def delete(self, request, user_id):
        user = get_object_or_404(CustomUser, pk=user_id)
        user.delete()
        return JsonResponse({'message': 'User deleted successfully'})

useracc/templates/activate_user.html
<!-- activate_user.html -->
{% extends 'base.html' %}

{% block content %}
<h2>Activate User</h2>
<form method="post">
    {% csrf_token %}

    <div>
        <label for="{{ form.is_staff.id_for_label }}">Is Staff:</label>
        {{ form.is_staff }}
    </div>

    <div>
        <label for="{{ form.is_superuser.id_for_label }}">Is Superuser:</label>
        {{ form.is_superuser }}
    </div>

    <div>
        <label for="{{ form.email_verified.id_for_label }}">Email Verified:</label>
        {{ form.email_verified }}
    </div>

    <div>
        <label for="{{ form.is_active.id_for_label }}">Is Active:</label>
        {{ form.is_active }}
    </div>

    <button type="submit">Activate</button>
</form>
<p><a href="{% url 'user_list' %}">Back to User List</a></p>
{% endblock %}

useracc/templates/edit_profile.html
{% extends 'back/base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Edit Profile</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.username.id_for_label }}">Username:</label>
            {{ form.username }}
            {% if form.username.errors %}
            <div style="color: red;">{{ form.username.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.first_name.id_for_label }}">First Name:</label>
            {{ form.firstname }}
            {% if form.firstname.errors %}
            <div style="color: red;">{{ form.firstname.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6 col-lg-5" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
            {{ form.lastname }}
            {% if form.lastname.errors %}
            <div style="color: red;">{{ form.lastname.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6 col-lg-5" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.gender.id_for_label }}">Gender:</label>
            {{ form.gender }}
            {% if form.gender.errors %}
            <div style="color: red;">{{ form.gender.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.email.id_for_label }}">Email:</label>
            {{ form.email }}
            {% if form.email.errors %}
            <div style="color: red;">{{ form.email.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.phone.id_for_label }}">Phone:</label>
            {{ form.phone }}
            {% if form.phone.errors %}
            <div style="color: red;">{{ form.phone.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 100%;">
            <label for="{{ form.profile.id_for_label }}">Profile Picture:</label>
            {{ form.profile }}
            {% if form.profile.errors %}
            <div style="color: red;">{{ form.profile.errors }}</div>
            {% endif %}
        </div>

        <button type="submit"
            style="width: 20%; padding: 10px; background-color: #4CAF50; color: #fff; border: none; cursor: pointer;">Save Changes</button>
    </form>
</div>
{% endblock %}

useracc/templates/home.html
<!-- myapp/templates/home.html -->
{% extends 'back/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h2>User List</h2>
<ul>
    {% for user in users %}
    <li>{{ user.username }} - {{ user.email }}</li>
    {% endfor %}
</ul>
{% endblock %}

useracc/templates/login.html
{% extends 'front/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="border border-3 border-primary rounded p-4" style="background-color: azure;">
                <h2 class="text-center mb-4">Login</h2>
                <form method="post">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="{{ form.username.id_for_label }}" class="form-label">Username:</label>
                        {{ form.username }}
                        {% if form.username.errors %}
                        <div class="text-danger">{{ form.username.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        <label for="{{ form.password.id_for_label }}" class="form-label">Password:</label>
                        {{ form.password }}
                        {% if form.password.errors %}
                        <div class="text-danger">{{ form.password.errors }}</div>
                        {% endif %}
                    </div>
                   <div class=" mt-3 " style="margin-left: 100px;"> 
                    <button type="submit" class="btn btn-primary">Login</button>  &nbsp &nbsp &nbsp &nbsp
                    <a href="{% url 'password_reset' %}" style="background-color: skyblue;">Forgot Password?</a>
                    
                </div>
                </form>

                

                <p class="mt-3" >
                    Don't have an account? &nbsp &nbsp &nbsp &nbsp <a href="{% url 'useracc:register' %}" style="background-color: skyblue;">Register</a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

useracc/templates/logout.html
<br><br><br>
Login 

<div style="padding: 20px;">

    {% if loggedin %}
    
    <h4> successfully logged in </h4>
    {% endif %}

    <form action="" method="POST" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group mb-3"> 
            <input type="text" name="email" autocomplete="email" class="form-control" id="user-name" placeholder="Your Email">

            <!-- {{form.email}} -->
            <!-- <input type="text" class="form-control" placeholder="email" aria-label="Recipient's username" aria-describedby="basic-addon2"> -->
        </div>
        <br><br>
        <div class="input-group mb-3">
            <input type="password" required  name="password" class="form-control" id="id_password" placeholder="Password">
            
            
                <!-- <i class="fa fa-eye" id="id_eye" title="Show Password" onclick="make_visible()">v</i> -->
           

            <!-- {{form.password}} -->
            <!-- <input type="text" class="form-control" placeholder="password" aria-label="Recipient's username" aria-describedby="basic-addon2"> -->
        </div>
        <br><br>


        <button type="submit"  class="btn btn-dark" >Log</button>
    </form>

</div>

useracc/templates/register.html
<!-- registration/register.html -->
{% extends 'back/base.html' %}

{% block content %}
<div style="margin: 0 auto; width: 50%;">
    <h2 style="text-align: center;">Register Staff</h2>
    <form method="post" enctype="multipart/form-data"
        style="margin: 0 auto; display: flex; flex-wrap: wrap; justify-content: space-between;">
        {% csrf_token %}

        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.username.id_for_label }}">Username:</label>
            {{ form.username }}
            {% if form.username.errors %}
            <div style="color: red;">{{ form.username.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.first_name.id_for_label }}">First Name:</label>
            {{ form.firstname }}
            {% if form.first_name.errors %}
            <div style="color: red;">{{ form.first_name.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
            {{ form.lastname }}
            {% if form.last_name.errors %}
            <div style="color: red;">{{ form.last_name.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.gender.id_for_label }}">Gender:</label>
            <br/>
            {{ form.gender }}
            {% if form.gender.errors %}
            <div style="color: red;">{{ form.gender.errors }}</div>
            {% endif %}
        </div>
 
        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.email.id_for_label }}">Email:</label> <br/>
            {{ form.email }}
            {% if form.email.errors %}
            <div style="color: red;">{{ form.email.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.phone.id_for_label }}">Phone:</label> <br/>
            {{ form.phone }}
            {% if form.phone.errors %}
            <div style="color: red;">{{ form.phone.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 100%;">
            <label for="{{ form.profile.id_for_label }}">Profile Picture:</label>
            {{ form.profile }}
            {% if form.profile.errors %}
            <div style="color: red;">{{ form.profile.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.password1.id_for_label }}">Password:</label>
            {{ form.password1 }}
            {% if form.password1.errors %}
            <div style="color: red;">{{ form.password1.errors }}</div>
            {% endif %}
        </div>

        <div class="col-md-6" style="margin-bottom: 10px; flex: 0 0 48%;">
            <label for="{{ form.password2.id_for_label }}">Confirm Password:</label>
            {{ form.password2 }}
            {% if form.password2.errors %}
            <div style="color: red;">{{ form.password2.errors }}</div>
            {% endif %}
        </div>

        <button type="submit"
            style="width: 100%; padding: 10px; background-color: #4CAF50; color: #fff; border: none; cursor: pointer;">Register</button>
    </form>

    <p style="text-align: center; margin-top: 20px;">Already have an account? <a href="{% url 'useracc:login' %}"
            style="color: #4CAF50; font-weight: bold;">Login</a></p>
</div>
{% endblock %}

useracc/templates/user_list.html
{% extends 'back/base.html' %}

{% block content %}
<section>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">User List</h4>
        </div>
        <div class="card-content">
          <div class="card-body card-dashboard">
            <table class="table table-striped table-bordered multi-ordering">
              <thead>
                <tr>
                  <th>Full Name</th>
                  <th>username</th>
                  <th>Email</th>
                  <th>superuser</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for user in users %}
                <tr>
                  <td>{{ user.full_name }}</td>
                  <td>{{ user.username }}</td>
                  <td>{{ user.email }}</td>
                  <td>{{ user.is_superuser }}</td>
                  <td>{{ user.status }}</td>
                  <td>
                    {% if user.is_activated %}
                    Activated
                    {% else %}
                    <span class="dropdown">
                      <a id="btnSearchDrop{{ user.id }}" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="true" class="dropdown-toggle dropdown-menu-right">
                        Actions</a>
                      <span aria-labelledby="btnSearchDrop{{ user.id }}" class="dropdown-menu mt-1 dropdown-menu-right">
                        <a href="{% url 'useracc:activate' user_id=user.pk %}" class="dropdown-item">
                          <i class="fa fa-check"></i> Activate User
                        </a>
                        <a href="#" class="dropdown-item"
                          onclick="confirmDelete('useracc', 'delete_user', '{{ user.id }}')">
                          <i class="fa fa-trash"></i> Delete User
                        </a>


                      </span>
                    </span>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    function confirmDelete(appName, viewName, userId) {
      var confirmation = confirm("Are you sure you want to delete this user?");
      if (confirmation) {
        var xhr = new XMLHttpRequest();
        var url = "/" + appName + "/" + viewName + "/" + userId + "/";
        xhr.open("DELETE", url);
        xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");

        // Include CSRF token in the header
        var csrftoken = getCookie('csrftoken');
        xhr.setRequestHeader("X-CSRFToken", csrftoken);


        // xhr.onload = function () {
        //   if (xhr.status === 200) {
        //     var response = JSON.parse(xhr.responseText);
        //     alert(response.message);
        //     // Optionally, you can redirect or refresh the page
        //     window.location.reload();
        //   } else {
        //     alert("Something went wrong: " + xhr.statusText);
        //   }
        // };
        xhr.send();
        window.location.reload();
      }
    }

    // Function to get CSRF token from cookies
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }

  </script>
</section>


{% endblock %}

useracc/templates/user_profile.html
<!-- profile.html -->
{% extends 'back/base.html' %}

{% block content %}
<div style="margin: 0 auto; width: 50%; text-align: center;">
    <h2>{{ user.username }}'s Profile</h2>
    {% if user.profile %}
    <img src="{{ user.profile.url }}" alt="Profile Picture" style="width: 150px; height: 150px; border-radius: 50%; margin-bottom: 20px;">
    {% else %}
    <h3> No Profile has been uploaded </h3>
    {% endif %}
    <table style="margin: 0 auto; width: 100%; text-align: left;">
        <tr>
            <th>UserName:</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>First Name:</th>
            <td>{{ user.firstname }}</td>
        </tr>
        <tr>
            <th>Last Name:</th>
            <td>{{ user.lastname }}</td>
        </tr>
        <tr>
            <th>Gender:</th>
            <td>{{ user.gender }}</td>
        </tr>
        <tr>
            <th>Email:</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Phone:</th>
            <td>{{ user.phone }}</td>
        </tr>
    </table>
    
    <p style="margin-top: 20px;">
        <a href="{% url 'useracc:edit_profile' %}" style="color: #4CAF50; font-weight: bold;">Edit Profile</a>
    </p>
</div>
{% endblock %}