ardi/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('terms-conditions/', TermsAndConditionsView.as_view(), name='terms_conditions'),
    path('privacy/', PrivacyView.as_view(), name='privacy'),
    path('faq/', FAQView.as_view(), name='faq'),
    path('warranty/', WarrantyView.as_view(), name='warranty'),
    path('care-maintenance/', CareAndMaintenanceView.as_view(), name='care_maintenance'),

    path('', Index.as_view(), name='index'),
    path('about/', About.as_view(), name='about'),
    path('gallery/', Galleries.as_view(), name='gallery'),
    path('products/', Products.as_view(), name='products'),
    path('products/<int:id>/', product_detail, name='product_detail'),
    path('testimonial/', Testimonials.as_view(), name='testimonials'),
    path('service/', Service.as_view(), name='service'),
    path('admin/', Dashboard.as_view(), name='dashboard'),

    path('product/', ListProduct.as_view(), name='list_product'),
    path('products/add/', AddProduct.as_view(), name='add_product'),
    path('products/edit/<int:id>/', EditProduct.as_view(), name='edit_product'),
    path('products/delete/<int:id>/', DeleteProduct.as_view(), name='delete_product'),
    path('products/image/delete/<int:id>/', DeleteProductImage.as_view(), name='delete_product_image'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('search/', ProductSearchView.as_view(), name='product_search'),


    path('galleries/', ListGallery.as_view(), name='list_gallery'),
    path('galleries/add/', AddGallery.as_view(), name='add_gallery'),
    path('galleries/edit/<int:id>/', EditGallery.as_view(), name='edit_gallery'),
    path('galleries/delete/<int:id>/', DeleteGallery.as_view(), name='delete_gallery'),
    path('galleries/image/delete/<int:id>/', DeleteImage.as_view(), name='delete_image'),

    path('testimonials/', ListTestimonial.as_view(), name='list_testimonial'),
    path('testimonials/add/', AddTestimonial.as_view(), name='add_testimonial'),
    path('testimonials/edit/<int:id>/', EditTestimonial.as_view(), name='edit_testimonial'),
    path('testimonials/delete/<int:id>/', DeleteTestimonial.as_view(), name='delete_testimonial'),

    path('contacts/', ListContact.as_view(), name='list_contact'),
    path('contacts/add/', AddContact.as_view(), name='add_contact'),
    path('contacts/delete/<int:id>/', DeleteContact.as_view(), name='delete_contact'),





    #
    #
    #
    path('homes/', ListHome.as_view(), name='list_home'),
    path('homes/add/', AddHome.as_view(), name='add_home'),
    path('homes/edit/<int:id>/', EditHome.as_view(), name='edit_home'),
    path('homes/delete/<int:id>/', DeleteHome.as_view(), name='delete_home'),
    path('homes/image/delete/<int:id>/', DeleteHomeImage.as_view(), name='delete_home_image'),
]

ardimarble/urls.py
# ardimarble/urls.py

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('ardi.urls')),
    path('useracc/', include('useracc.urls')),  # Added trailing slash
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'ardi.views.custom_404'

useracc/urls.py
from django.urls import path
from .views import *
app_name = 'useracc'

urlpatterns = [
    path('profile/<int:id>/', Profile.as_view(), name='profile'),
    path('profile/edit/', EditProfile.as_view(), name='edit_profile'),
    path('register/', Register.as_view(), name='register'),
    path('email-verify/<str:uidb64>/<str:token>/', EmailVerify.as_view(), name='email_verify'),
    path('activate/<int:user_id>/', Activate.as_view(), name='activate'),
    path('delete_user/<int:user_id>/', DeleteUser.as_view(), name='delete_user'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('staff-page/', StaffPage.as_view(), name='staff_page'),
    
]

templates/back/add_gallery.html
{% extends 'back/base.html' %}
{% load static %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'list_gallery' %}">Galleries</a></li>
<li class="breadcrumb-item">
    {% if gallery %}Edit Gallery{% else %}Add Gallery{% endif %}
</li>
{% endblock %}

{% block content %}
<div class="site-main">
    <section class="ttm-row clearfix">
        <div class="container">
            <div class="row pt-60 res-991-pt-0">
                <div class="col-lg-12">
                    <div class="pr-40 res-991-pr-0 res-991-pb-30">
                        <h4 class="h4-md">
                            {% if gallery %}Edit Gallery{% else %}Add Gallery{% endif %}
                        </h4>

                        <form action="{% if gallery %}{% url 'edit_gallery' id=gallery.id %}{% else %}{% url 'add_gallery' %}{% endif %}" method="POST" enctype="multipart/form-data" class="row">
                            {% csrf_token %}
                            <div class="col-md-6">
                                <div class="contact-form col-md-12 pb-2 input-patient">
                                    <p style="font-weight: 700;">Title</p>
                                    {{ gallery_form.title }}
                                    {{ gallery_form.errors.title }}
                                </div>
                            </div>
                        
                            <div class="col-md-6">
                                <div class="contact-form col-md-12 pb-2 input-patient">
                                    <p style="font-weight: 700;">Category</p>
                                    {{ gallery_form.category }}
                                    {{ gallery_form.errors.category }}
                                </div>
                            </div>
                        
                            <div class="col-md-12">
                                <div class="contact-form col-md-12 pb-2 input-patient">
                                    <p style="font-weight: 700;">Images</p>
                                    <input type="file" name="images" multiple>
                                    {{ image_form.errors.images }}
                                </div>
                            </div>
                        
                            <div class="col-md-12 mb-3">
                                <button type="submit" class="btn btn-primary">
                                    {% if gallery %}Update{% else %}Submit{% endif %}
                                </button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/back/base.html
{% load static %}
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
  <title>{% block main_title %} Ardi Marble {% endblock %}</title>

  <head>
    {% include 'back/head.html' %}
    {% block style %}
    {% endblock %}
  </head>
<!-- BEGIN: Body-->

  <body id="id_bar" class="vertical-layout vertical-menu-modern 2-columns   fixed-navbar " data-open="click"
    data-menu="vertical-menu-modern" data-col="2-columns">

    {% include 'back/header.html' %}

    <!-- BEGIN: Main Menu-->
    <div class="main-menu menu-fixed menu-dark menu-accordion menu-shadow expan" data-scroll-to-active="true">
      <div class="main-menu-content" style="margin-bottom: 40px; ">

        <ul class="navigation navigation-main " id="main-menu-navigation" data-menu="menu-navigation"
          style=" padding-bottom: 110px;">

          <li class=" nav-item navigation-header {% block dashboard %} {% endblock %}">
            <a href="{% url 'index' %}"><i class="fa fa-home"></i><span class="menu-title">View Site</span></a>
          </li>

          <br>

          <li class=" nav-item {% block index %} {% endblock %}">
            <a href="{% url 'dashboard' %}">
              <span class="menu-title">Dashboard </span>
            </a>

          </li>

          <li class=" nav-item ">
            <a href="#">
              <span class="menu-title"><i class="fa fa-list"></i>Product</span>
            </a>
            <ul class="menu-content">
              <li class=" nav-item"><a href=" {% url 'add_product' %}" class="menu-item"><span class="menu-title">Add
                    Products</span></a>
              </li>

              <li class=" nav-item"><a href="{% url 'list_product' %}" class="menu-item"><span class="menu-title">List
                    Products</span></a>
              </li>

              <li class=" nav-item"><a href=" " target="blank" class="menu-item">
                  <span class="menu-title"> Products on Site </span></a>
              </li>
            </ul>
          </li>

          <li class=" nav-item {% block gallery %} {% endblock %}">
            <a href="#">
              <span class="menu-title"><i class="fa fa-image"></i>Gallery</span>
            </a>
            <ul class="menu-content">
              <li class=" nav-item"><a href=" {% url 'add_gallery' %}" class="menu-item"><span
                    class="menu-title">Add Gallery</span></a>
              </li>

              <li class=" nav-item"><a href="{% url 'list_gallery' %}" class="menu-item"><span class="menu-title">List
                    Gallery</span></a>
              </li>

              <li class=" nav-item"><a href="" target="blank" class="menu-item">
                  <span class="menu-title"> Gallery on Site </span></a>
              </li>
            </ul>
          </li>

          <li class=" nav-item {% block testimonial %} {% endblock %}">
            <a href="#">
              <span class="menu-title"><i class="fa fa-file"></i>Testimonial</span>
            </a>
            <ul class="menu-content">
              <li class=" nav-item"><a href="{% url 'add_testimonial' %}" class="menu-item"><span
                    class="menu-title">Add Testimonial</span></a></li>

              <li class=" nav-item"><a href="{% url 'list_testimonial' %}" class="menu-item"><span class="menu-title">List
                    Testimonial</span></a></li>


              <li class=" nav-item"><a href="" target="blank" class="menu-item">
                  <span class="menu-title"> Testimonial on Site </span></a>
              </li>
            </ul>

          </li>

          <li class=" nav-item {% block contact %} {% endblock %}">
            <a href="#">
              <span class="menu-title"><i class="fa fa-envelope"></i>Messages</span>
            </a>
            <ul class="menu-content">

              <li class=" nav-item"><a href="{% url 'list_contact' %}" class="menu-item"><span class="menu-title">List
                    messages</span></a></li>


              <li class=" nav-item"><a href="{% url 'add_contact' %}" target="blank" class="menu-item">
                  <span class="menu-title"> Contact on Site </span></a>
              </li>
            </ul>

          </li>

          <li class=" nav-item {% block staff %} {% endblock %}">
            <a href="#">
              <span class="menu-title"><i class="fa fa-home"></i>Staff</span>
            </a>
            <ul class="menu-content">

              <li class=" nav-item"><a href="{% url 'useracc:staff_page' %}" class="menu-item"><span class="menu-title">List
                    Registered staffs</span></a></li>


              <li class=" nav-item"><a href="{% url 'useracc:register' %}" target="blank" class="menu-item">
                  <span class="menu-title"> Register New Staff </span></a>
              </li>
            </ul>

          </li>

          <br>
        </ul>
      </div>
    </div>
   <!--  END: Main Menu -->

        <!-- BEGIN: Content-->
    <div class="app-content content" style="background: #fff;">
      <div class="content-wrapper">

        <!--start message area -->
        <div id="id_messages_area" class="content-header row" style="width: 100%;">

          {% if messages %}
            {% for m in messages %}
              {% if 'success' in m.tags %}
              <div class="alert alert-icon-right alert-success alert-dismissible col-md-12" role="alert">
              {% elif 'warning' in m.tags %}
              <div class="alert alert-icon-right alert-warning alert-dismissible col-md-12" role="alert">
              {% elif 'error' in m.tags %}
              <div class="alert alert-icon-right alert-danger alert-dismissible col-md-12" role="alert">
              {% else %}
              <div class="alert alert-icon-right alert-info alert-dismissible col-md-12" role="alert">
              {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
                <strong></strong> {{m}} <a href="#" class="alert-link"></a>
              </div>

            {% endfor %}
          {% endif %}
        </div>
                  <!-- end message area -->


        <div class="content-header-left col-md-6 col-12 mb-2">
          <h3 class="content-header-title mb-0">{% block title %}{% endblock %}</h3>
          <div class="row breadcrumbs-top">
            <div class="breadcrumb-wrapper col-12">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">dashboard</a></li>
                {% block breadcrumb %} {% endblock %}
              </ol>
            </div>
          </div>
        </div>
        <div class="content-body" style="box-shadow: 4px 4px 10px #888888; padding: 20px;">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
              <!-- END: Content-->

          <!-- BEGIN: Footer-->
    <footer class="footer footer-static footer-light navbar-border">
      <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2"><span
          class="float-md-left d-block d-md-inline-block"> &copy; 2024 <a
            class="text-bold-800 text-center grey darken-2" href="#" target="_blank">Ardi</a></span><span
          class="float-md-right d-none d-lg-block">Developed by DebolEngineering</span>
      </p>
    </footer>
          <!-- END: Footer-->

          <!-- BEGIN: Vendor JS-->
    <script src="{% static 'staff/vendors/js/vendors.min.js' %}"></script>
    <script src="{% static 'staff/vendors/js/tables/datatable/datatables.min.js' %}"></script>

    <!-- BEGIN: Page Vendor JS-->
    <script src="{% static 'staff/js/scripts/tables/datatables/datatable-basic.min.js' %}"></script>
    <!-- END: Page Vendor JS-->

    <script src="{% static 'staff/js/core/app-menu.min.js' %}"></script>
    <script src="{% static 'staff/js/core/app.min.js' %}"></script>
        <!-- END: Theme JS-->

        <!-- BEGIN: Theme JS-->
        <!-- END: Page JS-->
    {% block js %}
    
    {% endblock %}
    <script src="{% static 'staff/js/scripts/compiled.min.js' %}"></script>




  </body>
<!-- END: Body-->

</html>

templates/back/header.html
{%load static %} 
<nav class="header-navbar navbar-expand-lg navbar navbar-with-menu fixed-top navbar-semi-dark navbar-shadow">
  <div class="navbar-wrapper">
    <div class="navbar-header" style = " background-color:skyblue; ">
      <ul class="nav navbar-nav flex-row">
        <li class="nav-item mobile-menu d-lg-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="fa fa-align-justify font-medium-3 "></i></a></li>
        <li class="nav-item mr-auto"><a class="" href="/"><img class="brand-logo mt-1" width="40px" height="40px" alt="Logo"  src="{% static 'images/ardi_logo.jpg' %}">
            </a>
        </li>

        <!-- <li class="nav-item d-none d-lg-block nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i class="toggle-icon fa fa-align-justify  right font-medium-3 white  icon-toggle-right" data-ticon=".icon-toggle-right"></i></a></li>
        <li class="nav-item d-lg-none"><a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="fa fa-ellipsis-v"></i></a></li> -->
      
      </ul>
    </div>
    <div class="navbar-container content" style = " background-color:skyblue; ">
      <div class="collapse navbar-collapse" id="navbar-mobile">

        <ul class="nav navbar-nav mr-auto float-left">
          
          <!-- <li class="nav-item d-none d-md-block"><a class="nav-link nav-link-expand" href="#"><i class="fa fa-window-maximize"></i></a></li>
          <li class="nav-item nav-search"><a class="nav-link nav-link-search" href="#"><i class="fa fa-search"></i></a>
            <div class="search-input">
              <input class="input" type="text" placeholder="Search a module..." tabindex="0" data-search="template-search">
              <div class="search-input-close"><i class="fa fa-times"></i></div>
              <ul class="search-list"></ul>
            </div>
          </li> -->
        </ul>
        
        <ul class="nav navbar-nav float-right">


					{% if user.is_authenticated %}
            <li class="dropdown dropdown-user nav-item">
              <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                <div class="avatar avatar-online" style="width:32px; height: 32px;">
                  {% if user.profile %} 
                    <img  style="width: 32px; height: 32px;" src="{{user.profile.url}}" alt="user profile image">
                  {% else %}
                  <img style="width: 32px; height: 32px;" src="{% static 'front/img/user.png' %}" alt="avatar">
                  {% endif %}
                </div>
                <span class="user-name">{% if user %} {{user.full_name}} {% endif %}</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{% url 'useracc:profile' id=user.id %}">My Profile</a>
              
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" onclick="return confirm('Do you want to Logout?') " href="{% url 'useracc:logout' %}">
                   Logout
                </a>
              </div>
            </li>
          {% else %}
          <a class=" pt-2 pr-3" href="{% url 'useracc:login' %}" style="font-size: 16px;">
            Signin </a>
          {% endif %}


        </ul>
      </div>
    </div>
  </div>
</nav>  

templates/back/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section >


    <div class="row">
        <div class="col-12">
            <div class="card">


                <div class="col-lg-12 col-sm-12 border-right-blue-grey border-right-lighten-5 clearfix mb-1 mt-1">
                    <div class="media">
                        <div class="media-left pr-1">
                            <img class="media-object" height="95" width="95" {% if user.profile %} src="{{user.profile.url}}" {% else %} src="{% static 'front/img/user.png' %}"  {% endif %} alt="Profile Image">
                        </div>
                        <div class="media-body pt-1 pb-0">
                            <a href="{% url 'useracc:profile' id=user.id %}"><h4 class="card-title">{{user.full_name}}</h4></a>
                            <p>{{user.email}}</p>
                        </div>
                    </div>
                </div>


                <div class="row">
                   
                    
                    <div class="col-lg-12 col-sm-12">
                        <div class="card" style="height: 378.1px;">
                            <div class="card-header border-0">
                                <h4 class="card-title">Staff Members ({{users.count}})</h4>
                                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <ul class="list-inline mb-0">
                                        <li><a data-action="reload"><i class="feather icon-rotate-cw"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-content">
                                <div id="audience-list-scroll" class="table-responsive height-300 position-relative">
                                    <table class="table mb-0">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Email</th>
                                                <th>Phone</th>
                                                <th>Status</th>
                                                <th>Registered Date</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for u in users %}
                                            <tr>
                                                <td> <a href=""> {{u.full_name}}</a></td>
                                                <td>{{u.email}}</td>
                                                <td>{{u.phone}}</td>
                                                <td>{{u.status}}</td>
                                                <td>{{u.created_date}}</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>
    


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="row">
                    <div class="col-lg-6 col-sm-12">
                        <div class="card" style="height: 378.1px;">
                            <div class="card-header border-0">
                                <h4 class="card-title"> Research Outputs ({{research.count}})</h4>
                                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <ul class="list-inline mb-0">
                                        <li><a data-action="reload"><i class="feather icon-rotate-cw"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-content">
                                <div id="audience-list-scroll" class="table-responsive height-300 position-relative">
                                    <table class="table mb-0">
                                        <thead>
                                            <tr>
                                                <th>Title</th>
                                                <th>Author</th>
                                                <th>Document</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for r in research %}
                                            <tr>
                                                <td> <a href="{% url 'staff:research_update' id=r.id %}"> {{r.title}}</a></td>
                                                <td>{{r.author}}</td>
                                                <td>{% if r.document %} <a href="{{r.document.url}}" download> Download</a>{% else %} No Doc {% endif %}</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div> 
                    
                    <div class="col-lg-6 col-sm-12">
                        <div class="card" style="height: 378.1px;">
                            <div class="card-header border-0">
                                <h4 class="card-title">Active Call Applications ({{call_application.count}})</h4>
                                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <ul class="list-inline mb-0">
                                        <li><a data-action="reload"><i class="feather icon-rotate-cw"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-content">
                                <div id="audience-list-scroll" class="table-responsive height-300 position-relative">
                                    <table class="table mb-0">
                                        <thead>
                                            <tr>
                                                <th>Title</th>
                                                <th>Assistant Name</th>
                                                <th>Email</th>
                                                <th>End Date</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for c in call_application %}
                                            <tr>
                                                <td> <a href="{% url 'staff:call_application_update' id=c.id %}"> {{c.title}}</a></td>
                                                <td>{{c.assistant_name}}</td>
                                                <td>{{c.email}}</td>
                                                <td>{{c.end_date}}</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>



    
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="row">
                    <div class="col-lg-6 col-sm-12">
                        <div class="card" style="height: 378.1px;">
                            <div class="card-header border-0">
                                <h4 class="card-title"> Upcoming Events ({{event.count}})</h4>
                                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <ul class="list-inline mb-0">
                                        <li><a data-action="reload"><i class="feather icon-rotate-cw"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card-content">
                                <div id="audience-list-scroll" class="table-responsive height-300 position-relative">
                                    <table class="table mb-0">
                                        <thead>
                                            <tr>
                                                <th>Title</th>
                                                <th>Place</th>
                                                <th>Date</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for e in event %}
                                            <tr>
                                                <td> <a href="{% url 'staff:events_update' id=e.id %}"> {{e.title}}</a></td>
                                                <td>{{e.place}}</td>
                                                <td>{{e.date}}</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div> 
                    
                </div>
            </div>
        </div>
    </div>

</section>
{% endblock %}